### PR TITLE
Replace obsolete org-bracket-link-regexp variable

### PR DESCRIPTION
**Pull request by bcc32**

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks.

When did this variable change?  If we make this change, what versions of Org will be incompatible?

**Comment by bcc32** [comment]
The old variable was obsoleted in org 9.3, which is the same version where the new variable was added.  If that's too new, I could replace it with a `boundp` check, or maybe we should just continue to use the old variable name?

**Comment by alphapapa** [comment]
What versions of Emacs include Org versions older than 9.3?  Are they still in common use?  (e.g. are they still the versions distributed in current versions of major Linux distros?)

Generally changes like this, which AFAIK only prevent a compilation warning upon installation, are not very important, and should be delayed nearly as long as possible, to prevent breaking functionality for users on older versions.  

But if it bothers you enough, the fix should usually define a new variable that is conditionally initialized to whichever one is in the user's version of Org.

**Comment by bcc32** [comment]
> What versions of Emacs include Org versions older than 9.3? Are they still in common use? (e.g. are they still the versions distributed in current versions of major Linux distros?)

Good question, and I don't really have any idea.

> Generally changes like this, which AFAIK only prevent a compilation warning upon installation, are not very important, and should be delayed nearly as long as possible, to prevent breaking functionality for users on older versions.

I basically submitted this just for compilation warning cleanliness reasons, but I agree that avoiding breakage is more important.  Happy to just close the PR, thanks for reviewing!

> But if it bothers you enough, the fix should usually define a new variable that is conditionally initialized to whichever one is in the user's version of Org.

**Pull request closed without merging**
